common/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

from common.views import (
    ChangePasswordView,
    CompanyLoginView,
    CreateUserView,
    DocumentDeleteView,
    DocumentDetailView,
    DocumentListView,
    ForgotPasswordView,
    HomeView,
    # LoginView,
    LogoutView,
    PasswordResetView,
    ProfileView,
    RegistrationView,
    UpdateUserView,
    UserDeleteView,
    UserDetailView,
    UsersListView,
    activate_user,
    add_api_settings,
    add_comment,
    api_settings,
    change_passsword_by_admin,
    change_user_status,
    check_sub_domain,
    create_lead_from_site,
    delete_api_settings,
    document_create,
    document_update,
    download_attachment,
    download_document,
    edit_comment,
    get_teams_and_users,
    google_login,
    landing_page,
    remove_comment,
    resend_activation_link,
    update_api_settings,
    view_api_settings,
)

app_name = "common"


urlpatterns = [
    path("", landing_page, name="landing_page"),
    path("dashboard/", HomeView.as_view(), name="dashboard"),
    path("login/", CompanyLoginView.as_view(), name="login"),
    #     path('login/', LoginView.as_view(), name='login'),
    path("register/", RegistrationView.as_view(), name="register"),
    path("auth/domain/", check_sub_domain, name="check_domain"),
    path("forgot-password/", ForgotPasswordView.as_view(), name="forgot_password"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path("profile/", ProfileView.as_view(), name="profile"),
    # User views
    path("users/list/", UsersListView.as_view(), name="users_list"),
    path("users/create/", CreateUserView.as_view(), name="create_user"),
    path("users/<int:pk>/edit/", UpdateUserView.as_view(), name="edit_user"),
    path("users/<int:pk>/view/", UserDetailView.as_view(), name="view_user"),
    path("users/<int:pk>/delete/", UserDeleteView.as_view(), name="remove_user"),
    path("password-reset/", PasswordResetView.as_view(), name="password_reset"),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    # Document
    path("documents/", DocumentListView.as_view(), name="doc_list"),
    path("documents/create/", document_create, name="create_doc"),
    path("documents/<int:pk>/edit/", document_update, name="edit_doc"),
    path("documents/<int:pk>/view/", DocumentDetailView.as_view(), name="view_doc"),
    path("documents/<int:pk>/delete/", DocumentDeleteView.as_view(), name="remove_doc"),
    # download
    path("documents/<int:pk>/download/", download_document, name="download_document"),
    # download_attachment
    path(
        "attachments/<int:pk>/download/",
        download_attachment,
        name="download_attachment",
    ),
    path("user/status/<int:pk>/", change_user_status, name="change_user_status"),
    path("comment/add/", add_comment, name="add_comment"),
    path("comment/<int:pk>/edit/", edit_comment, name="edit_comment"),
    path("comment/remove/", remove_comment, name="remove_comment"),
    # settings
    path("api/settings/", api_settings, name="api_settings"),
    path("api/settings/add/", add_api_settings, name="add_api_settings"),
    path("api/settings/<int:pk>/", view_api_settings, name="view_api_settings"),
    path(
        "api/settings/<int:pk>/update/", update_api_settings, name="update_api_settings"
    ),
    path(
        "api/settings/<int:pk>/delete/", delete_api_settings, name="delete_api_settings"
    ),
    path(
        "change-password-by-admin/",
        change_passsword_by_admin,
        name="change_passsword_by_admin",
    ),
    path("google/login/", google_login, name="google_login"),
    path("create-lead-from-site/", create_lead_from_site, name="create_lead_from_site"),
    # user activate link
    path(
        "activate-user/<uidb64>/<token>/<activation_key>/",
        activate_user,
        name="activate_user",
    ),
    path(
        "resend_activation_link/<userId>/",
        resend_activation_link,
        name="resend_activation_link",
    ),
    path("get_teams_and_users/", get_teams_and_users, name="get_teams_and_users"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500

app_name = "crm"

urlpatterns = [
    path("", include("common.urls", namespace="common")),
    path("", include("django.contrib.auth.urls")),
    path("marketing/", include("marketing.urls", namespace="marketing")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("leads/", include("leads.urls", namespace="leads")),
    path("contacts/", include("contacts.urls", namespace="contacts")),
    path("opportunities/", include("opportunity.urls", namespace="opportunities")),
    path("cases/", include("cases.urls", namespace="cases")),
    path("tasks/", include("tasks.urls", namespace="tasks")),
    path("invoices/", include("invoices.urls", namespace="invoices")),
    path("events/", include("events.urls", namespace="events")),
    path("teams/", include("teams.urls", namespace="teams")),
    path("emails/", include("emails.urls", namespace="emails")),
    # path('planner/', include('planner.urls', namespace="planner")),
    path("logout/", views.LogoutView, {"next_page": "/login/"}, name="logout"),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )


handler404 = handler404
handler500 = handler500

teams/urls.py
from django.urls import path
from teams.views import teams_list, team_create, team_edit, team_delete, team_detail


app_name = "teams"


urlpatterns = [
    path("", teams_list, name="teams_list"),
    path("create/", team_create, name="team_create"),
    path("edit/<int:team_id>/", team_edit, name="team_edit"),
    path("delete/<int:team_id>/", team_delete, name="team_delete"),
    path("detail/<int:team_id>/", team_detail, name="team_detail"),
]

cases/models.py
import arrow
from django.db import models
from django.utils.translation import pgettext_lazy
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from accounts.models import Account
from contacts.models import Contact
from common.models import User, Company
from common.utils import CASE_TYPE, PRIORITY_CHOICE, STATUS_CHOICE
from planner.models import Event
from teams.models import Teams


class Case(models.Model):
    name = models.CharField(pgettext_lazy("Name of the case", "Name"), max_length=64)
    status = models.CharField(choices=STATUS_CHOICE, max_length=64)
    priority = models.CharField(choices=PRIORITY_CHOICE, max_length=64)
    case_type = models.CharField(
        choices=CASE_TYPE, max_length=255, blank=True, null=True, default=""
    )
    account = models.ForeignKey(
        Account, on_delete=models.CASCADE, blank=True, null=True
    )
    contacts = models.ManyToManyField(Contact)
    # closed_on = models.DateTimeField()
    closed_on = models.DateField()
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(User, related_name="case_assigned_users")
    created_by = models.ForeignKey(
        User, related_name="case_created_by", on_delete=models.SET_NULL, null=True
    )
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    is_active = models.BooleanField(default=False)
    teams = models.ManyToManyField(Teams, related_name="cases_teams")
    company = models.ForeignKey(
        Company, on_delete=models.SET_NULL, null=True, blank=True
    )

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.name

    @property
    def get_team_users(self):
        team_user_ids = list(self.teams.values_list("users__id", flat=True))
        return User.objects.filter(id__in=team_user_ids)

    @property
    def get_team_and_assigned_users(self):
        team_user_ids = list(self.teams.values_list("users__id", flat=True))
        assigned_user_ids = list(self.assigned_to.values_list("id", flat=True))
        user_ids = team_user_ids + assigned_user_ids
        return User.objects.filter(id__in=user_ids)

    @property
    def get_assigned_users_not_in_teams(self):
        team_user_ids = list(self.teams.values_list("users__id", flat=True))
        assigned_user_ids = list(self.assigned_to.values_list("id", flat=True))
        user_ids = set(assigned_user_ids) - set(team_user_ids)
        return User.objects.filter(id__in=list(user_ids))

    def get_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type,
            object_id=self.id,
            event_type="Meeting",
            status="Planned",
        )

    def get_completed_meetings(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Meeting"
        ).exclude(status="Planned")

    def get_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type,
            object_id=self.id,
            event_type="Task",
            status="Planned",
        )

    def get_completed_tasks(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Task"
        ).exclude(status="Planned")

    def get_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type,
            object_id=self.id,
            event_type="Call",
            status="Planned",
        )

    def get_completed_calls(self):
        content_type = ContentType.objects.get(app_label="cases", model="case")
        return Event.objects.filter(
            content_type=content_type, object_id=self.id, event_type="Call"
        ).exclude(status="Planned")

    def get_assigned_user(self):
        return User.objects.get(id=self.assigned_to.id)

    @property
    def created_on_arrow(self):
        return arrow.get(self.created_on).humanize()

teams/models.py
import arrow

from django.db import models
from common.models import User, Company
from django.utils.translation import ugettext_lazy as _


class Teams(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    users = models.ManyToManyField(User, related_name="user_teams")
    created_on = models.DateTimeField(_("Created on"), auto_now_add=True)
    created_by = models.ForeignKey(
        User,
        related_name="teams_created",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    company = models.ForeignKey(
        Company, on_delete=models.SET_NULL, null=True, blank=True
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("id",)

    @property
    def created_on_arrow(self):
        return arrow.get(self.created_on).humanize()

    def get_users(self):
        return ",".join(
            [str(_id) for _id in list(self.users.values_list("id", flat=True))]
        )
        # return ','.join(list(self.users.values_list('id', flat=True)))

teams/views.py
from datetime import date, datetime, timedelta

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    FormView,
    TemplateView,
    UpdateView,
    View,
)

from common.models import User
from teams.models import Teams
from teams.forms import TeamForm
from teams.tasks import update_team_users, remove_users


@login_required
def teams_list(request):
    context = {}
    if request.user.role == "ADMIN" or request.user.is_superuser:
        queryset = Teams.objects.filter(company=request.company).order_by("-created_on")
        users = User.objects.filter(company=request.company)
        context["teams"] = queryset
        context["users"] = users
    else:
        raise PermissionDenied

    if request.method == "GET":
        user_ids = list(queryset.values_list("created_by", flat=True))
        user_ids.append(request.user.id)
        context["created_by_users"] = users.filter(is_active=True, id__in=user_ids)
        return render(request, "teams.html", context)
    if request.method == "POST":
        if request.POST.get("team_name"):
            queryset = queryset.filter(name__icontains=request.POST.get("team_name"))
        if request.POST.get("created_by"):
            queryset = queryset.filter(created_by=request.POST.get("created_by"))
        if request.POST.get("assigned_to"):
            queryset = queryset.filter(
                users__id__in=request.POST.getlist("assigned_to")
            )
        context["assigned_to"] = request.POST.getlist("assigned_to")
        context["teams"] = queryset
        user_ids = list(queryset.values_list("created_by", flat=True))
        user_ids.append(request.user.id)
        context["created_by_users"] = users.filter(is_active=True, id__in=user_ids)
        return render(request, "teams.html", context)


@login_required
def team_create(request):
    context = {}
    if request.user.role == "ADMIN" or request.user.is_superuser:
        teams = Teams.objects.filter(company=request.company)
        context["teams"] = teams
    else:
        raise PermissionDenied

    if request.method == "GET":
        form = TeamForm(request_obj=request)
        context["form"] = form
        return render(request, "team_create.html", context)

    if request.method == "POST":
        form = TeamForm(request.POST, request_obj=request)
        if form.is_valid():
            task_obj = form.save(commit=False)
            task_obj.created_by = request.user
            task_obj.company = request.company
            task_obj.save()
            form.save_m2m()
            return JsonResponse(
                {"error": False, "success_url": reverse("teams:teams_list")}
            )
        else:
            return JsonResponse({"error": True, "errors": form.errors})


@login_required
def team_detail(request, team_id):
    if not (request.user.role == "ADMIN" or request.user.is_superuser):
        raise PermissionDenied
    team_obj = get_object_or_404(Teams, pk=team_id)
    if team_obj.company != request.company:
        raise PermissionDenied
    context = {}

    if request.method == "GET":
        context["team_obj"] = team_obj
        return render(request, "team_detail.html", context)


@login_required
def team_edit(request, team_id):
    if not (request.user.role == "ADMIN" or request.user.is_superuser):
        raise PermissionDenied
    team_obj = get_object_or_404(Teams, pk=team_id)
    if team_obj.company != request.company:
        raise PermissionDenied
    actual_users = team_obj.get_users()
    context = {}

    if request.method == "GET":
        form = TeamForm(instance=team_obj, request_obj=request)
        context["form"] = form
        return render(request, "team_create.html", context)

    if request.method == "POST":
        removed_users = []
        form = TeamForm(request.POST, instance=team_obj, request_obj=request)
        if form.is_valid():
            task_obj = form.save(commit=False)
            if "users" in form.changed_data:
                update_team_users.delay(team_id)
                # pass
            task_obj.save()
            form.save_m2m()
            latest_users = task_obj.get_users()
            for user in actual_users:
                if user in latest_users:
                    pass
                else:

                    removed_users.append(user)
            remove_users.delay(removed_users, team_id)
            return JsonResponse(
                {"error": False, "success_url": reverse("teams:teams_list")}
            )
        else:
            return JsonResponse({"error": True, "errors": form.errors})


@login_required
def team_delete(request, team_id):
    if not (request.user.role == "ADMIN" or request.user.is_superuser):
        raise PermissionDenied
    team_obj = get_object_or_404(Teams, pk=team_id)
    if team_obj.company != request.company:
        raise PermissionDenied
    context = {}

    if request.method == "GET":
        team_obj.delete()
        return redirect("teams:teams_list")

teams/templates/teams.html
{% extends 'sales/base.html' %}
{% load static %}
{% load paginate %}
{% load thumbnail %}
{% block extralinks %}
<style>
  .form-group label {
    font-weight: 800;
  }
</style>
{% endblock %}
{% block content %}

<div class="main_container">
  
  <div class="row marl">
    <div class="col-lg-12 text-right">
      <span class="d-inline"><a class="primary_btn" href="{% url 'teams:team_create'%}"><i class="fa fa-plus"></i>
          Add New
          Team</a></span>
    </div>
  </div>
  
  <div class="filter_row list_filter_row row marl">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <form id="leads_filter" action="" method="POST">
            <div class="card-body ">
              <div class="card-title">Filters</div>
              <div class="row marl">
                <div class="filter_col col-md-2">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Team Name</label>
                    <input type="text" class="form-control" placeholder="Team Name" name="team_name"
                      value="{{request.POST.team_name}}">
                  </div>
                </div>
                <div class="filter_col col-md-2">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Created By</label>
                    <select name="created_by" id="created_by" class="assigned_users_ form-control">
                      <option value="">
                        ------------------</option>
                      {% for user in created_by_users %}
                      <option value="{{user.id}}" {% if user.id|slugify == request.POST.created_by %} selected=""
                        {% endif %}>
                        {{user.email}}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <div class="filter_col col-md-2">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Assigned Users</label>
                    <select class="assigned_users form-control" name="assigned_to" multiple="multiple">
                      {% for user in users %}
                      <option value="{{user.id}}" {% if user.id|slugify in assigned_to %} selected="" {% endif %}>
                        {% if user.username %}{{user.username}}{% else %}{{user.email}}{% endif %}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <input type="hidden" name="tab_status" id="tab_status">
                <div class="filter_col col-2">
                  <div class="form-group buttons_row">
                    <button class="btn btn-primary save" type="submit">Search</button>
                    <a href="{% url 'teams:teams_list' %}" class="btn btn-default clear">Clear</a>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-12 col-lg-12 col-xl-12">
    <div class="table_container_row row marl no-gutters">
      <div class="col-md-12">
        
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active" id="open" role="tabpanel" aria-labelledby="open">
            <div class="card">
              <div class="card-body">
                <div class="card-title text-right">
                  <span class="float-left">Teams - {% if show_pageitems %}
                    {% show_pageitems %}{% else %}
                    {{ teams|length }}{% endif %}</span>
                  <span class="filter_toggle">
                    <a href="#" class="primary_btn"><i class="fas fa-filter"></i></a>
                  </span>
                </div>
                <div class="table-responsive">
                  <table class="table ">
                    <thead>
                      {% if teams|length > 0 %}
                      <tr>
                        <th width="5%">ID</th>
                        <th width="5%">Team Name</th>
                        <th width="15%">Team Description</th>
                        <th width="10%">Assigned To</th>
                        <th width="5%">Created by</th>
                        <th width="5%">Created On</th>
                        <th width="10%">Actions</th>
                      </tr>
                      {% endif %}
                    </thead>
                    <tbody>
                      {% if per_page %}
                      {% paginate per_page teams %}
                      {% else %}
                      {% paginate 10 teams %}
                      {% endif %}
                      {% for team in teams %}
                      <tr class="text-center">
                        <td scope="row">{{ forloop.counter }}</td>
                        <td><a href="#" data-toggle="modal" data-target="#exampleModalCenter_team{{team.id}}">
                            {{ team.name }} </a></td>
                        <td class="">
                          {% if team.description %}
                          {{ team.description }}
                          {% else %}
                          None
                          {% endif %}
                        </td>
                        <td>
                          {% with users=team.users.all %}
                          {% for user in users %}
                          {% if user.profile_pic %}
                          {% thumbnail user.profile_pic "40x40" crop="center" as im %}
                          <a href="{% url 'common:view_user' user.id %}">
                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
                              title="{{ user.email }}">
                          </a>
                          {% endthumbnail %}
                          {% else %}
                          <a href="{% url 'common:view_user' user.id %}">
                            <img src="{% static 'images/user.png' %}" title="{{ user.email }}" width="40" height="40">
                          </a>
                          {% endif %}
                          {% empty %}
                          None
                          {% endfor %}
                          {% endwith %}
                        </td>
                        <td>
                          {% if team.created_by %}
                          {% if team.created_by.profile_pic %}
                          {% thumbnail team.created_by.profile_pic "40x40" crop="center" as im %}
                          <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
                            title="{{ team.created_by }}" style="border-radius: 50%" />
                          {% endthumbnail %}
                          {% else %}
                          <img src="{% static 'images/user.png' %}" style="width: 40px;height: 40px;border-radius: 50%;"
                            title="{{ team.created_by }}" />
                          {% endif %}
                          {% else %}
                          None
                          {% endif %}
                        </td>
                        <td title="{{ team.created_on }}">{{ team.created_on_arrow }}</td>
                        <td class="actions">
                          {% if request.user == team.created_by or request.user.role == 'ADMIN' or reques.user.is_superuser %}
                          <a href="{% url 'teams:team_detail' team.id %}" class="btn btn-info edit" title="View"><i
                              class="fas fa-eye"></i></a>
                          <a href="{% url 'teams:team_edit' team.id %}" class="btn btn-success edit" title="Edit"><i
                              class="fas fa-pencil-alt"></i></a>
                          <a href="{% url 'teams:team_delete' team.id %}"
                            class="btn btn-danger delete remove_document" title="Delete"><i class="fas fa-trash-alt"></i></a>
                          {% endif %}
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
                {%ifequal teams|length 0%}
                <h6 class="text-center">No Teams Found</h6>
                {%endifequal%}
                <div class="marl row text-center">
                  {% show_pages %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% for team_obj in teams %}
<div class="modal fade" id="exampleModalCenter_team{{team_obj.id}}" tabindex="-1" role="dialog"
  aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">{{ team_obj.name }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="" id="">
          <div class="">
            <div class="col-md-12">
              <div class="card">
                <div class="card-body" id="datashow" >
                  
                  <div class="row marl no-gutters">
                    <div class="col-md-8">
                      {% if team_obj.name %}
                      
                      {% endif %}
                      {% if team_obj.description %}
                      <div class="filter_col col-md-12">
                        <div class="form-group">
                          <label class="contact_field_label" for="id_status" data-name="status">Description</label>
                          <div class="contact_field" id="doc_status" data-name="status">
                            {{ team_obj.description }} </div>
                        </div>
                      </div>
                      {% endif %}
                      <div class="filter_col col-md-12">
                        <div class="form-group">
                          <label class="contact_field_label" for="id_status" data-name="status">Assigned To</label>
                          <br>
                          {% with users=team_obj.users.all %}
                          {% for user in users %}
                          {% if user.profile_pic %}
                          {% thumbnail user.profile_pic "40x40" crop="center" as im %}
                          <span>
                            <a href="{% url 'common:view_user' user.id %}">
                              <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
                                title="{{ user.email }}">
                            </a>
                          </span>
                          {% endthumbnail %}
                          {% else %}
                          <span>
                            <a href="{% url 'common:view_user' user.id %}">
                              <img src="{% static 'images/user.png' %}" title="{{ user.email }}" width="40" height="40">
                            </a>
                          </span>
                          {% endif %}
                          {% empty %}
                          None
                        </div>
                      </div>
                      {% endfor %}
                      {% endwith %}
                      <div class="filter_col col-md-12" style="margin-left: -1em;">
                        <div class="form-group mt-3">
                          <label class="contact_field_label" for="id_created_by" data-name="created_by">Created
                            By</label>
                          <div class="contact_field" id="created_by" data-name="created_by">
                            {{ team_obj.created_by }}</div>
                        </div>
                      </div>
                      <div class="filter_col col-md-12" style="margin-left: -1em;">
                        <div class="form-group">
                          <label class="contact_field_label" for="id_created_on" data-name="created_on">Created
                            On</label>
                          <div class="contact_field" id="created_on" data-name="created_on" title="{{team_obj.created_on}}">
                            {{ team_obj.created_on_arrow }}</div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</div>
</div>
</div>

{% endfor %}

{% endblock %}
{% block js_block %}
<script type="text/javascript">
  $(document).ready(function () {
    $('.assigned_users').select2();
    $('#id_tag').select2();
    $('#created_by').select2();
    $(".filter_toggle").click(function () {
      $(".list_filter_row").toggle();
    });
  });

  search = "{{search}}"

  if (search == 'True') {
    $(".list_filter_row").show();
  }

  $("#close-tab").click(function (e) {
    $("#tab_status").val('Closed')
  })

  $("#open-tab").click(function (e) {
    $("#tab_status").val('Open')
  })

  tab_status = "{{tab_status}}"
  if (tab_status == 'Closed') {
    $("#close-tab").click()
  } else {
    $("#open-tab").click()
  }

  $('.delete').click(function (e) {
    e.preventDefault()
    url = $(this).attr('href')
    if (!confirm('Are you sure you want to delete?'))
      return;
    window.location = $(this).attr('href')
  });

  $("a[rel='page']").click(function (e) {
    e.preventDefault();
    $('#leads_filter').attr("action", $(this).attr("href"));
    $('#leads_filter').submit();
  });
</script>
{% endblock js_block %}