cases/urls.py
from django.urls import path
from cases.views import (
    CasesListView,
    create_case,
    CaseDetailView,
    update_case,
    RemoveCaseView,
    CloseCaseView,
    select_contact,
    GetCasesView,
    AddCommentView,
    UpdateCommentView,
    DeleteCommentView,
    get_teams_and_users,
    AddAttachmentView,
    DeleteAttachmentsView,
)

app_name = "cases"

urlpatterns = [
    path("", CasesListView.as_view(), name="list"),
    path("create/", create_case, name="add_case"),
    path("<int:pk>/view/", CaseDetailView.as_view(), name="view_case"),
    path("<int:pk>/edit_case/", update_case, name="edit_case"),
    path("<int:case_id>/remove/", RemoveCaseView.as_view(), name="remove_case"),
    path("close_case/", CloseCaseView.as_view(), name="close_case"),
    path("select_contacts/", select_contact, name="select_contacts"),
    path("get/list/", GetCasesView.as_view(), name="get_cases"),
    path("comment/add/", AddCommentView.as_view(), name="add_comment"),
    path("comment/edit/", UpdateCommentView.as_view(), name="edit_comment"),
    path("comment/remove/", DeleteCommentView.as_view(), name="remove_comment"),
    path("attachment/add/", AddAttachmentView.as_view(), name="add_attachment"),
    path(
        "attachment/remove/", DeleteAttachmentsView.as_view(), name="remove_attachment"
    ),
    path("get_teams_and_users/", get_teams_and_users, name="get_teams_and_users"),
]

common/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

from common.views import (
    ChangePasswordView,
    CompanyLoginView,
    CreateUserView,
    DocumentDeleteView,
    DocumentDetailView,
    DocumentListView,
    ForgotPasswordView,
    HomeView,
    # LoginView,
    LogoutView,
    PasswordResetView,
    ProfileView,
    RegistrationView,
    UpdateUserView,
    UserDeleteView,
    UserDetailView,
    UsersListView,
    activate_user,
    add_api_settings,
    add_comment,
    api_settings,
    change_passsword_by_admin,
    change_user_status,
    check_sub_domain,
    create_lead_from_site,
    delete_api_settings,
    document_create,
    document_update,
    download_attachment,
    download_document,
    edit_comment,
    get_teams_and_users,
    google_login,
    landing_page,
    remove_comment,
    resend_activation_link,
    update_api_settings,
    view_api_settings,
)

app_name = "common"


urlpatterns = [
    path("", landing_page, name="landing_page"),
    path("dashboard/", HomeView.as_view(), name="dashboard"),
    path("login/", CompanyLoginView.as_view(), name="login"),
    #     path('login/', LoginView.as_view(), name='login'),
    path("register/", RegistrationView.as_view(), name="register"),
    path("auth/domain/", check_sub_domain, name="check_domain"),
    path("forgot-password/", ForgotPasswordView.as_view(), name="forgot_password"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path("profile/", ProfileView.as_view(), name="profile"),
    # User views
    path("users/list/", UsersListView.as_view(), name="users_list"),
    path("users/create/", CreateUserView.as_view(), name="create_user"),
    path("users/<int:pk>/edit/", UpdateUserView.as_view(), name="edit_user"),
    path("users/<int:pk>/view/", UserDetailView.as_view(), name="view_user"),
    path("users/<int:pk>/delete/", UserDeleteView.as_view(), name="remove_user"),
    path("password-reset/", PasswordResetView.as_view(), name="password_reset"),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    # Document
    path("documents/", DocumentListView.as_view(), name="doc_list"),
    path("documents/create/", document_create, name="create_doc"),
    path("documents/<int:pk>/edit/", document_update, name="edit_doc"),
    path("documents/<int:pk>/view/", DocumentDetailView.as_view(), name="view_doc"),
    path("documents/<int:pk>/delete/", DocumentDeleteView.as_view(), name="remove_doc"),
    # download
    path("documents/<int:pk>/download/", download_document, name="download_document"),
    # download_attachment
    path(
        "attachments/<int:pk>/download/",
        download_attachment,
        name="download_attachment",
    ),
    path("user/status/<int:pk>/", change_user_status, name="change_user_status"),
    path("comment/add/", add_comment, name="add_comment"),
    path("comment/<int:pk>/edit/", edit_comment, name="edit_comment"),
    path("comment/remove/", remove_comment, name="remove_comment"),
    # settings
    path("api/settings/", api_settings, name="api_settings"),
    path("api/settings/add/", add_api_settings, name="add_api_settings"),
    path("api/settings/<int:pk>/", view_api_settings, name="view_api_settings"),
    path(
        "api/settings/<int:pk>/update/", update_api_settings, name="update_api_settings"
    ),
    path(
        "api/settings/<int:pk>/delete/", delete_api_settings, name="delete_api_settings"
    ),
    path(
        "change-password-by-admin/",
        change_passsword_by_admin,
        name="change_passsword_by_admin",
    ),
    path("google/login/", google_login, name="google_login"),
    path("create-lead-from-site/", create_lead_from_site, name="create_lead_from_site"),
    # user activate link
    path(
        "activate-user/<uidb64>/<token>/<activation_key>/",
        activate_user,
        name="activate_user",
    ),
    path(
        "resend_activation_link/<userId>/",
        resend_activation_link,
        name="resend_activation_link",
    ),
    path("get_teams_and_users/", get_teams_and_users, name="get_teams_and_users"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import include, path
from common.views import handler404, handler500

app_name = "crm"

urlpatterns = [
    path("", include("common.urls", namespace="common")),
    path("", include("django.contrib.auth.urls")),
    path("marketing/", include("marketing.urls", namespace="marketing")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("leads/", include("leads.urls", namespace="leads")),
    path("contacts/", include("contacts.urls", namespace="contacts")),
    path("opportunities/", include("opportunity.urls", namespace="opportunities")),
    path("cases/", include("cases.urls", namespace="cases")),
    path("tasks/", include("tasks.urls", namespace="tasks")),
    path("invoices/", include("invoices.urls", namespace="invoices")),
    path("events/", include("events.urls", namespace="events")),
    path("teams/", include("teams.urls", namespace="teams")),
    path("emails/", include("emails.urls", namespace="emails")),
    # path('planner/', include('planner.urls', namespace="planner")),
    path("logout/", views.LogoutView, {"next_page": "/login/"}, name="logout"),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )


handler404 = handler404
handler500 = handler500

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load compress %}
{% load thumbnail %}
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{APPLICATION_NAME}}</title>
    <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />

    {% compress css %}
    <link href="{% static 'css/main.scss' %}" type="text/x-scss" rel="stylesheet">
    <link href="{% static 'css/mention.scss' %}" type="text/x-scss" rel="stylesheet">
    {% endcompress %}
    {% block extralinks %} {% endblock %}
  </head>
  <body class="main_body_bg_color">
    <div class="wrapper">

      <header>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top">

          <a class="navbar-brand" href="{% url 'common:dashboard' %}">{{APPLICATION_NAME}}</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
          </button>
          {% if request.user.is_authenticated %}
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item"><a class="nav-link" id="dashboard" href="{% url 'common:dashboard' %}">Dashboard</a></li>
              {% if request.user.role == "ADMIN"  or request.user.is_superuser %}
              <li class="nav-item"><a class="nav-link" id="users" href="{% url 'common:users_list' %}">Users</a></li>
              {% endif %}
              <li class="nav-item"><a class="nav-link" id="accounts" href="{% url 'accounts:list' %}">Accounts</a></li>
              <li class="nav-item"><a class="nav-link" id="contacts" href="{% url 'contacts:list' %}">Contacts</a></li>
              <li class="nav-item"><a class="nav-link" id="leads" href="{% url 'leads:list' %}">Leads</a></li>
              <li class="nav-item"><a class="nav-link" id="opportunities"href="{% url 'opportunities:list' %}">Opportunities</a></li>
              <li class="nav-item"><a class="nav-link" id="cases" href="{% url 'cases:list' %}">Cases</a></li>
              <li class="nav-item"><a class="nav-link" id="documents" href="{% url 'common:doc_list' %}">Documents</a></li>
              {% if request.user.role == "ADMIN" or request.user.is_superuser %}
              <li class="nav-item"><a class="nav-link" id="users" href="{% url 'common:api_settings' %}">Settings</a></li>
              {% endif %}
            </ul>
            <ul class="navbar-nav navbar-right my-2 my-lg-0">
              <li class="nav-item dropdown">
                <a href="#" class="dropdown-toggle abcd nav-link" data-toggle="dropdown" role="button" aria-haspopup="true"
                  aria-expanded="false" >
                {% if not request.user.profile_pic %}
                <img src="{% static 'images/user.png' %}" alt="Micro profile pic">
                {% else %}
                {% thumbnail request.user.profile_pic "25x25" as im %}
                <img src="{{ im.url }}">
                {% endthumbnail %}
                {% endif %}
                <b class="caret"></b></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  {% if request.user.email != "admin@micropyramid.com" %}
                  <a class="dropdown-item" href="/change-password/"><i class="fas fa-key"></i> Change Password</a>
                  {% endif %}
                  <a class="dropdown-item" href="{% url 'common:profile' %}"><i class="fas fa-user"></i> Profile</a>
                  <a class="dropdown-item" href="{% url 'common:logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
                </div>
              </li>
            </ul>
          </div>
          {% else %}
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto my-2 my-lg-0">
              <li class="nav-item"><a class="nav-link" id="dashboard" href="{% url 'common:dashboard' %}">Login</a></li>
            </ul>
          </div>
          {% endif %}
        </nav>
      </header>

      <div id="mainbody" class="main_container" style="padding-top:65px;">

        {% block breadcrumb %}
        {% endblock %}

        {% block content %}
        {% endblock %}
      </div>

    </div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    {% block js_block %}
    {% endblock js_block %}
    <script type="text/javascript">
      $(document).ready(function(){
          word = window.location.pathname.split('/')[1]
          if(word == ""){
            $("#dashboard").addClass('active')
          }
          else{
            $('#' + word).addClass('active')
          }
      });
    </script>
  </body>
</html>

templates/check_subdomain.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <div class="row marl justify-content-center login_row">
    <div class="col-md-6 col-lg-6 col-xl-4">
      <div class="login_block">
        <div class="login_form_block">
          <div class="welcome">{{ APPLICATION_NAME }}</div>
          <form method="POST" action="">
            <div class="form-group">
              <input type="text" class="form-control" id="id_sub_domain" placeholder="subdomain.bottle.crm"
                name="sub_domain" value="{{request.POST.sub_domain}}">
              <span class="error">
                <ul class="errorlist">
                  <li>
                    {{error}}
                  </li>
                </ul>
              </span>
            </div>
            <div class="forgot">New Here? <a href="{% url "common:register" %}">Register</a></div>
            <div class="forgot">Forgot Password <a href="{% url "common:password_reset" %}">Click Here?</a></div>

            <button type="submit" class="btn btn-danger">Login</button>

          </form>

        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/login.html
{% load static %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ settings.APPLICATION_NAME }}</title>

  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/css/bootstrap.min.css" />
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js"></script>

  {% compress css %}
  <link href="{% static 'css/main.scss' %}" type="text/x-scss" rel="stylesheet">
  {% endcompress %}
  {% block extralinks %}{% endblock %}
</head>

<body class="login_register_body">
  {% if messages %}
  <ul style="font-size: 1.5em;" class="text-center mt-5">
    {% for message in messages %}
    {{ message|safe }}
    {% endfor %}
  </ul>
  {% endif %}
  <div class="container">
    <div class="row marl justify-content-center login_row">
      <div class="col-md-6 col-lg-6 col-xl-4">
        <div class="login_block">
          <div class="login_form_block">
            <div class="welcome">{{ settings.APPLICATION_NAME }}</div>
            <form method="POST" action="">
              <div class="form-group">
                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Email" name="email">
                <span class="error">{{form.email.errors}}</span>
              </div>
              <div class="form-group">
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password"
                  name="password">
                <span class="error">{{form.password.errors}}</span>
              </div>
              <div class="forgot">New Here? <a href="{% url "common:register" %}">Register</a></div>
              <div class="forgot">Forgot Password <a href="{% url "common:password_reset" %}">Click Here?</a></div>
              {% if error %}
              <p class="error">{{ message }}</p>
              {% endif %}
              <button type="submit" class="btn btn-danger">Login</button>
              &nbsp;
              {% if ENABLE_GOOGLE_LOGIN and GP_CLIENT_SECRET and GP_CLIENT_ID %}
              <a href="{% url 'common:google_login' %}" class="btn btn-primary">Google Login</a>
              {% endif %}
            </form>

          </div>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

templates/new_user.html
hello {{user.email}},

<p>Your account has been successfully created in Django CRM by {{created_by.email}}</p>

templates/registration.html
{% extends 'sales/base.html' %}
{% block content %}
<h1>Registration</h1>
<form method="POST" class="user-form">
  {{ reg_form.as_p }}
  <button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

templates/root.html
{% load static %}
{% load compress %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ settings.APPLICATION_NAME }}</title>
  <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />

  <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
  <link href="https://cdn.quilljs.com/1.3.6/quill.bubble.css" rel="stylesheet">
  <link href="https://cdn.quilljs.com/1.3.6/quill.core.css" rel="stylesheet">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/css/select2.min.css" integrity="sha256-FdatTf20PQr/rWg+cAKfl6j4/IY3oohFAJ7gVC3M34E=" crossorigin="anonymous" />

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />

  <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-tagsinput/1.3.6/jquery.tagsinput.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/start/jquery-ui.css" />
  <style>
    .card-body {
      padding:0;
      margin:0
    }
    .select2-container--default .select2-results__option[aria-disabled=true] {
      display: none;
    }
  </style>

  {% compress css %}
  <link href="{% static 'css/main.scss' %}" type="text/x-scss" rel="stylesheet">
  <link href="{% static 'css/mention.scss' %}" type="text/x-scss" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/bootstrap-suggest.css' %}">
  {% endcompress %}

  {% block extralinks %} {% endblock %}
</head>

<body class="main_body_bg_color">
  <div class="wrapper">
    {% block header %}
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
        <div class="dropdown">

            {% if request.user.is_superuser or request.user.role == 'ADMIN' %}
            <a class="dropdown-toggle navbar-brand" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false" style="color:#44535c">
            {{ settings.APPLICATION_NAME }}
            </a>
            {% else %}
            {% if request.user.has_sales_access and request.user.has_marketing_access %}
            <a class="dropdown-toggle navbar-brand" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false" style="color:#44535c">
            {{ settings.APPLICATION_NAME }}
            </a>
            {% elif request.user.has_sales_access and not request.user.has_marketing_access %}
            <a class="navbar-brand" href="{% url 'common:dashboard' %}" role="button" id="dropdownMenuLink" data-toggle=""
            aria-haspopup="true" aria-expanded="false" style="color:#44535c">
            {{ settings.APPLICATION_NAME }}
            </a>
            {% elif not request.user.has_sales_access and request.user.has_marketing_access %}
            <a class="navbar-brand" href="{% url 'marketing:dashboard' %}" role="button" id="dropdownMenuLink" data-toggle=""
            aria-haspopup="true" aria-expanded="false" style="color:#44535c">
            {{ settings.APPLICATION_NAME }}
            </a>
            {% else %}
            {{''}}
            {% endif %}
            {% endif %}

          <div class="dropdown-menu mt-2" aria-labelledby="dropdownMenuLink">
            {% if user.is_superuser or user.role == 'ADMIN' %}
            <a class="dropdown-item" href="/">Sales</a>
            <a class="dropdown-item" href="{% url 'marketing:dashboard' %}">Marketing</a>
            {% else %}
            {% if user.has_sales_access and user.has_marketing_access %}
            <a class="dropdown-item" href="/">Sales</a>
            <a class="dropdown-item" href="{% url 'marketing:dashboard' %}">Marketing</a>
            {% elif user.has_sales_access and not user.has_marketing_access %}
            <a class="dropdown-item" href="/">Sales</a>
            {% elif not user.has_sales_access and user.has_marketing_access %}
            <a class="dropdown-item" href="{% url 'marketing:dashboard' %}">Marketing</a>
            {% else %}
            {{''}}
            {% endif %}
            {% endif %}
          </div>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fas fa-bars"></i>
        </button>
        {% if request.user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          {% block main_menu %}{% endblock %}

          <ul class="navbar-nav navbar-right my-2 my-lg-0">
            <li class="nav-item dropdown">
              <a href="#" class="dropdown-toggle abcd nav-link" data-toggle="dropdown" role="button"
                aria-haspopup="true" aria-expanded="false">
                {% if not request.user.profile_pic %}
                <img src="{% static 'images/user.png' %}" alt="Micro profile pic">
                {% else %}
                {% thumbnail request.user.profile_pic "25x25" as im %}
                <img src="{{ im.url }}">
                {% endthumbnail %}
                {% endif %}
                <b class="caret"></b>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                {% if request.user.role == "ADMIN"  or request.user.is_superuser %}
                <a class="dropdown-item" href="{% url 'common:users_list' %}">Users</a>
                <a class="dropdown-item" href="{% url 'common:api_settings' %}">Settings</a>
                {% endif %}
                {% if request.user.email != "admin@micropyramid.com" %}
                <a class="dropdown-item" href="/change-password/">Change Password</a>
                {% endif %}
                <a class="dropdown-item" href="{% url 'common:profile' %}">Profile</a>
                <a class="dropdown-item" href="{% url 'common:logout' %}">Logout</a>
              </div>
            </li>
          </ul>
        </div>
        {% endif %}
      </nav>
    </header>
    {% endblock %}

    <div id="mainbody" class="main_container" style="margin-top:65px;">
      {% block breadcrumb %}
      {% endblock %}

      {% block content %}
      {% endblock %}
    </div>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment-with-locales.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>

  <script defer src="https://use.fontawesome.com/releases/v5.12.1/js/all.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>

  <script src="https://cdn.quilljs.com/1.3.6/quill.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.70/jquery.blockUI.min.js"></script>

<script src="{% static 'js/ajaxForm.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/js/select2.min.js" integrity="sha256-wfVTTtJ2oeqlexBsfa3MmUoB77wDNRPqT1Q1WA2MMn4=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js" integrity="sha256-+C0A5Ilqmu4QcSPxrlGpaZxJ04VjsRjKu+G82kl5UJk=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha256-WqU1JavFxSAMcLP2WIOI+GB2zWmShMI82mTpLDcqFUg=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha256-KM512VNnjElC30ehFwehXjx1YCHPiQkOPmqnrWtpccM=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-tagsinput/1.3.6/jquery.tagsinput.min.js" integrity="sha256-IkytFcY/Z/rLvRE9rYyZvybaitAWr1y2jS/+eyxXky8=" crossorigin="anonymous"></script>
<script src="https://malsup.github.io/jquery.form.js"></script>

<script src="http://cdn.ckeditor.com/4.5.4/basic/ckeditor.js"></script>

<script src="{% static 'js/bootstrap-suggest.js' %}"></script>

  {% block js_block %}{% endblock js_block %}
  <script type="text/javascript">
    $(document).ready(function () {
      word = window.location.pathname.split('/')[1];
      if (word == "") {
        $("#dashboard").addClass('active');
      }
      else {
        $('#' + word).addClass('active');
      }
      marketing_word = window.location.pathname.split('/')[2];
      if (marketing_word == "") {
        $("#marketing-dashboard").addClass('active');
      }
      // console.log(marketing_word.substring(0,7) === 'contact');
      else if (marketing_word.substring(0, 7) === "contact") {
        $("#contact").css({ 'border-bottom': '3px solid #099CBE,' });
        $(".contact_class").css('border-bottom', '3px solid #099CBE');
        marketing_word = window.location.pathname.split('/')[2]
        // console.log(marketing_word)
        // console.log(marketing_word == 'contact-list')
        // console.log(marketing_word == 'contacts')
        if (marketing_word == 'contact-list') {
          $(".contact-list").css('background', '#e5e5e5');
        }
        if (marketing_word == 'contacts') {
          $(".contacts").css('background', '#e5e5e5');
        }
      }
      else {
        $('#' + marketing_word).addClass('active')
      }
    });

  </script>
</body>

</html>